### ISSUE TITLE
Flowtype error

### ISSUE THREAD

**Issue by clarkdo** [leebyron/iterall#36]
node_modules/iterall/index.js:98:6

> Unable to determine module type (CommonJS vs ES) if both an export statement and module.exports are used in the same
module!

**Comment by clarkdo** [comment]
It should have been fixed, I will upgrade the package.

**Comment by clarkdo** [comment]
According to my investigating, the reason should be that the built `index.js` is `CommonJS` modules.export, but the flow comment is `ES module` export.

**Comment by leebyron** [comment]
Thanks for the report. @calebmer also mentioned this. I’ll look into a fix.

**Comment by leebyron** [comment]
@calebmer, I merged the flow definitions into the source file via flow comments, but the compilation to CJS is what results in the difference. If I create an index.js.flow will that suffice? I shouldn’t need one for index.mjs since that had the flow defs matching, right?

**Comment by SpainTrain** [comment]
> If I create an index.js.flow will that suffice?

This was my initial thought upon encountering this issue and FWIW would work for my use case.

However, the bummer with including types in a package is that newer versions of Flow might break older type definitions.  In a pre-1.0.0 world, I generally lobby for type defs in https://github.com/flowtype/flow-typed, since they are scoped to compatible Flow versions.
