### ISSUE TITLE
failing when running jest tests

### ISSUE THREAD

**Issue by mabellLU** [leebyron/iterall#43]
getting this error:

 export var $$iterator = SYMBOL_ITERATOR || '@@iterator'
    ^^^^^^

    SyntaxError: Unexpected token export

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at Object.<anonymous> (node_modules/graphql-tools/dist/stitching/observableToAsyncIterable.js:46:17)
      at Object.<anonymous> (node_modules/graphql-tools/dist/stitching/makeRemoteExecutableSchema.js:45:35)

**Comment by leebyron** [comment]
Thanks for the report - could you share more about the environment you had set up which resulted in this issue?

Seems like the same issue as https://github.com/graphql/graphql-js/issues/1248

**Comment by leebyron** [comment]
Looks like this is an issue with projects started with `create-react-app` and I've opened https://github.com/facebook/create-react-app/pull/4085 to solve for it.

I'll keep this issue open to track progress.

**Comment by gaearon** [comment]
If your project is built with Create React App and not ejected, `react-scripts@1.1.2` should fix this.
Here is how to upgrade:

https://github.com/facebook/create-react-app/releases/tag/v1.1.2

Otherwise you can apply a [similar fix](https://github.com/facebook/create-react-app/pull/4085/files) yourself in your project config. Cheers!
